### ISSUE TITLE
HUB75 64x64?

### ISSUE THREAD

**Issue by 1liminal1** [Manut38/WLED-GifPlayer-html#3]
Hey there, 

I tried using this and could get it uploaded to the file system. Can access it from device/gifplayer.htm. Can upload the gif

![image](https://github.com/user-attachments/assets/5302d2dc-ea3a-4cdb-8f3e-b3274ec3834c)

![image](https://github.com/user-attachments/assets/62c807b1-4fd9-4094-bc8a-4005fcdd4ed7)

But, none of the functionality works. I cant play gifs, I cant save as preset

Is it the 64x64 size?

Thanks

**Comment by Manut38** [comment]
Hi,

Soo, right now, in order to use this project at all you would have to manually build your own WLED binary using the [gif branch](https://github.com/Aircoookie/WLED/tree/gif) and flash it to your ESP32.
It seems like the https://github.com/Aircoookie/WLED/pull/3835 hasn't received much love lately and is quite outdated by now.

If you don't mind the little outdated WLED version of the current gif branch you could use this project with a build of the gif branch right now and it should work out of the box.
If I find the time, I will manually try to merge the image effect into the latest 0.15.0 beta version and report back if I could make it  work.
Anyway, the code in this repo should be unaffected, as long as the JSON api does not change dramatically or if the FX_IMAGE_EFFECT gets assigned a different ID than 53. This might happen though, when (or if) they ever decide to merge the feature into a stable version.

**Comment by 1liminal1** [comment]
Ahh ok, I'm actually stuck using moon modules for the time being, its the only one that supports HUB75 displays. 

Ill have to work out how I can add usermods to it. 

Thank you :)
